### ISSUE TITLE
How to interpret "Spatial Object" fields?

### ISSUE THREAD

**Issue by troychard** [AlteryxNed/Open_AlteryxYXDB#1]
Hi ColoradoNed,

I tried out the library to read a yxdb file and it works great!  I can read all the various fields of data.

But, I tried to read a "spatial" object field. eg: 
```
          SRC::BlobVal blob = pField->GetAsSpatialBlob(pRec).value;
          WriteBufferToFile(blob.pValue, blob.nLength, sTempShapeFileName);
```
where WriteBufferToFile(..) just calls
```
  FILE* pFile;
  string ansiFileName = ToAnsiString(fileName);
  pFile = fopen(ansiFileName.c_str(), "wb");
  fwrite(data, 1, numBytes, pFile);
  fclose(pFile);
```

This will create a file on disk with a name like "Record1.shp"

I tried to read the SHP file using [ShapeLib](http://shapelib.maptools.org/), but it doesn't seem to work without an .shx file.

So then I tried code I found here to [read a shp file header](https://www.igismap.com/c-program-read-shapefile-header/).   
This code seems to give me valid data when I give it a valid .shp file ( from a separate program )

But, when I try to pass it the data written from the blob field above, the numbers are all incorrect-looking in the debugger.

* Does the blob data represent a .shp file as is, or is there some extra manipulation required?
   * eg: Is it a shz file with the shp and shx inside?    Or are there a few bytes I need to skip past in the blob before the shp data?
* Do I have to change the byte order when writing it to disk?  ( I see shp files have mixed little-endian and big-endian fields in the header ).
* I assume blob.nLength is the length of the blob in bytes.

Just curious if there's something obvious I'm doing wrong or overlooking?

Regards,
Troy

**Comment by NedHarding** [comment]
Hey Troy,

First - I have not been part of Alteryx for more than 5 years.  So I am not answering in any official way and I have no access to the internal code.

From memory - the blob in question is not a SHP file, but a SHP record in little-endian.  I believe it starts with "Main File Record Contents" in the [SHP spec](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf).  You might have to poke around a bit to find exactly how it lines up.

If you are writing spatial records - it is important that you get the winding order correct on polygons otherwise it may look like there are bugs in other Alteryx tools.  This is detailed in the SHP spec.  Alteryx (like most GIS software) relies on proper winding order for operations like contains and merge.  Also not all SHP types would be supported - like probably not the *Z and *M variants.

Good luck,

Ned.

**Comment by troychard** [comment]
Thanks Ned!   That's super handy to know!!     I'll get back in there for round 2 asap and have another crack at it!    Thank-you again!

**Comment by troychard** [comment]
Thanks again Ned!    I just successfully decoded .shp data from a YXDB file!!! :D   That Winding Order was critical to determining difference between top-level enclosing rings versus holes!  (now time for celebratory coffee)  Thank-you again! :D :D
